# Node.js 18 slim image for dev
FROM node:18-slim

# Install pnpm
RUN corepack enable && corepack prepare pnpm@8.15.4 --activate

WORKDIR /app

# COPY package.json pnpm-lock.yaml ./
ENV CI=true
# RUN pnpm install --frozen-lockfile

# Copy rest of source (for caching, we copy after install step)
COPY . .
RUN pnpm install

EXPOSE 3000
CMD ["pnpm","dev","-p","3000"] 