version: "3.9"

services:
  app:
    container_name: duwallet-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    command: pnpm dev -p 3000
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    depends_on:
      - supabase-db

  supabase-db:
    image: supabase/postgres:15.1.0
    container_name: supabase-db
    restart: unless-stopped
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: supabase
      POSTGRES_USER: supabase
      POSTGRES_DB: supabase
    volumes:
      - supabase_data:/var/lib/postgresql/data

volumes:
  supabase_data: 