id: T-11-user-settings
name: "ユーザー設定画面 (S-11) 実装"
description: |
  ユーザー設定画面 (S-11) のUIと機能を実装する。
  プロフィール情報（名前、性別）の編集、アカウント設定（複数家計簿参加設定）、セキュリティ設定（パスワード変更）、アカウント削除機能を提供する。
  データは users テーブル (D-01) と連携し、ユーザー設定ストア (user-settings-store.ts) も利用する。
status: pending
depends_on: [T-04-wallet-navigation] # user-settings-store を利用するため
outputs:
  - "S-11 ユーザー設定画面の完成されたUI（S-11_user_settings.yaml 準拠）"
  - "プロフィール情報（名前、性別）の編集・保存機能"
  - "複数家計簿参加設定の変更機能（user-settings-store.ts と users テーブル連携）"
  - "パスワード変更機能（現在のパスワード確認、新しいパスワードと確認入力、バリデーション）"
  - "アカウント削除機能（確認ダイアログ付き、関連データ削除考慮）"
  - "users テーブル (D-01) への更新・削除処理"
steps:
  - id: 1
    name: "S-11 UIレイアウト実装"
    description: "S-11_user_settings.yaml に基づき、ヘッダー、プロフィールセクション、アカウント設定セクション、セキュリティセクション、危険な操作セクション、保存・キャンセルボタンの基本レイアウトを実装。"
  - id: 2
    name: "ユーザー情報読込・表示機能実装"
    description: "ログインユーザーの情報を users テーブルから読み込み、フォームの各フィールド（名前、Eメール(読み取り専用)、性別、複数家計簿参加設定）に表示する。複数家計簿参加設定は user-settings-store.ts の値も参照し、適切な disabled_condition を適用。"
  - id: 3
    name: "プロフィール情報（名前、性別）編集・保存機能実装"
    description: "編集された名前、性別を users テーブルに保存する処理を実装。"
  - id: 4
    name: "複数家計簿参加設定 更新機能実装"
    description: "変更された複数家計簿参加設定を users テーブルに保存し、user-settings-store.ts の状態も更新する。S-11_user_settings.yaml の disabled_condition（複数の家計簿に実際に参加している場合は「一つのみ参加」にできない）を適切に処理する。"
  - id: 5
    name: "パスワード変更機能実装"
    description: "現在のパスワード、新しいパスワード、新しいパスワード（確認）を入力させ、Supabase Authを利用してパスワードを変更する機能を実装。入力バリデーション（8文字以上、一致確認など）も行う。"
  - id: 6
    name: "アカウント削除機能実装"
    description: "ユーザーアカウントを削除する機能を実装。削除前に確認ダイアログを表示。users テーブルから該当レコードを削除。Supabase Auth からもユーザーを削除。関連する家計簿メンバーシップや収支データ等の扱いも考慮（要検討・実装）。削除後はタイトル画面へ遷移。"
  - id: 7
    name: "設定保存機能実装"
    description: "画面上の全ての変更内容（プロフィール、アカウント設定）を一括で users テーブルに保存する機能を実装。パスワード変更は別途専用の処理フローとする。"
  - id: 8
    name: "遷移元画面への戻り機能実装"
    description: "ユーザー設定画面に遷移してきた元の画面（家計簿ホーム画面 or 家計簿選択画面）に応じて、保存・キャンセル時に適切に戻る機能を実装 (S-11_user_settings.yaml の return_screen パラメータ利用)。"
created_at: 2025-05-17T10:40:00+09:00
updated_at: 2025-05-17T10:40:00+09:00
logs:
  - "2025-05-17: タスクファイル作成" 