- id: T-01-setup-environment
  name: 開発・CI/CD・本番環境セットアップ
  description: duwalletの全環境を正確に構築する
  status: done
  depends_on: []
  outputs:
    - .env.local
    - ローカル/CI/CD/本番環境のセットアップ完了
    - 必要なSecrets/Token/IDの登録
  created_at: 2025-05-15T00:10:00+09:00
  updated_at: 2025-05-15T00:10:00+09:00
  logs:
    - 2025-05-15: 旧appのdeploy.yml/ci.ymlを現行リポジトリの.github/workflows/に移行し、CI/CD運用ルールに統合。
    - 2025-05-15: docs/setup/Secrets_Env_Guide.mdにVERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_IDの用途・設定場所を追記。
    - 2025-05-15: CI/CDパイプラインの動作検証を実施。
    - 2025-05-15: T-01-setup-environmentタスク id:0〜8 完了。全工程完了。

- id: T-02-sync-project-structure
  name: プロジェクト構成・依存パッケージの設計同期
  description: docs/設計（ディレクトリ構成・技術スタック・画面仕様）と現行プロジェクトの齟齬を解消し、運用ルールに完全準拠した状態にする
  status: done
  depends_on: [T-01-setup-environment]
  outputs:
    - lib/
    - components/
    - hooks/
    - stores/
    - types/
    - src/app/(auth)/, (wallet)/, (user)/
    - package.json（設計通りの依存・バージョン）
    - 齟齬修正コミット
  created_at: 2025-05-16T00:00:00+09:00
  updated_at: 2025-05-16T00:00:00+09:00
  logs:
    - 2025-05-16: タスク登録
    - 2025-05-16: タスク完了・done/へ移動