# duwallet タスク管理DAG
version: 1
pending:
  - id: T-01-setup-environment
    name: 開発・CI/CD・本番環境セットアップ
    description: duwalletの全環境を正確に構築する
    status: pending
    depends_on: []
    outputs:
      - .env.local
      - ローカル/CI/CD/本番環境のセットアップ完了
      - 必要なSecrets/Token/IDの登録
    created_at: 2024-06-10T12:00:00Z
    updated_at: 2024-06-10T12:00:00Z
    logs: []
done: [] 