id: T-04B
title: Book Create Page
description: |
  • 画面 B-02 BookCreate (/books/new) を実装し、新規家計簿を作成できるようにする。
  • コンポーネント:
    - BookCreateForm (react-hook-form + zod validation)
  • Supabase `books` テーブルに INSERT、`book_users` 自動追加 (admin=true) を行う RPC または Edge Function は不要、Supabase Policy で許可。
  • フォーム送信後、/books/:id に遷移し Home を開くリダイレクト処理。
  • 単体テスト: BookCreateForm validation パターン。
  • Playwright: CreateBook シナリオ (book を作成しリダイレクト確認)。
dependsOn: [T-04A]
outputs:
  - apps/web/src/app/books/new/page.tsx
  - apps/web/src/components/client/BookCreateForm.tsx
  - tests/component/BookCreateForm.test.tsx
  - e2e/CreateBook.spec.ts
status: pending
