id: T-06
title: Calculation Settings & Logic
description: |
  • Implement C-04 CalcSettings screen and components: CalcMethodSelector, RoundDigitInput, IncomeSourceSelector, RatioAdjustmentTable
  • Edge Function: recalc_monthly (Supabase deploy & tests)
  • Integrate calc_logic.yaml formulas into function
  • Unit tests for calculation library with provided testVectors
  • Playwright test: adjust settings and verify payable displayed
  • Ensure RLS admin_update policy works
dependsOn: [T-05]
outputs:
  - apps/web/src/app/books/[id]/settings/calc/page.tsx
  - supabase/functions/recalc_monthly/index.ts
  - tests/unit/calc/index.spec.ts
  - e2e/CalcSettings.spec.ts
status: pending 