id: T-06A
title: CalcSettings UI
description: |
  • C-04 CalcSettings (/books/:bookId/settings/calc) 画面を実装。
  • コンポーネント:
    - CalcMethodSelector
    - RoundDigitInput
    - IncomeSourceSelector
    - RatioAdjustmentTable
  • Zod スキーマで設定データバリデーション。
  • 単体テスト: RatioAdjustmentTable 行追加ロジック。
  • Playwright: UpdateCalcSettings シナリオ。
dependsOn: [T-05C]
outputs:
  - apps/web/src/app/books/[id]/settings/calc/page.tsx
  - apps/web/src/components/client/CalcMethodSelector.tsx
  - apps/web/src/components/client/RoundDigitInput.tsx
  - apps/web/src/components/client/IncomeSourceSelector.tsx
  - apps/web/src/components/client/RatioAdjustmentTable.tsx
  - tests/component/RatioAdjustmentTable.test.tsx
  - e2e/UpdateCalcSettings.spec.ts
status: pending
