id: T-06B
title: Calc Edge Function Implementation
description: |
  • Supabase Edge Function `recalc_monthly` を実装 (Deno)。
  • calc_logic.yaml の数式を取り込み、指定 bookId の entries, settings, payees を集約し payable を計算。
  • RLS service_role key を使用したユニットテスト (deno test) を追加。
dependsOn: [T-06A]
outputs:
  - supabase/functions/recalc_monthly/index.ts
  - supabase/tests/recalc_monthly.test.ts
status: pending
