id: T-05-wallet-home
name: "家計簿ホーム画面 (S-05) 詳細機能実装"
description: |
  家計簿ホーム画面 (S-05) の主要機能であるサマリー表示 (ユーザー別収支、共通収支、全体合計)、
  月移動機能、サイドバーメニューによる各機能へのナビゲーションを実装する。
  表示データは関連テーブルから適切に取得・集計する。
status: pending
depends_on: [T-04-wallet-navigation]
outputs:
  - "S-05 家計簿ホーム画面の完成されたUI（S-05_wallet_home.yaml 準拠）"
  - "ユーザー別月次収支サマリー表示機能"
  - "ユーザー共通月次収支サマリー表示機能"
  - "全ユーザー月次収支・支払額合計表示機能"
  - "月次支払期限リスト表示機能"
  - "月移動（前月・次月）機能と、それに伴うデータ再取得・表示更新ロジック"
  - "ハンバーガーメニューとサイドバーナビゲーションの実装"
  - "income_expenses, payment_destinations テーブル等からのデータ取得・集計ロジック"
steps:
  - id: 1
    name: "S-05 UIレイアウト実装"
    description: "S-05_wallet_home.yaml に基づき、ヘッダー（家計簿名、月セレクタ、ハンバーガーメニュー）、サマリーカード、支払期限カードの基本レイアウトを実装。"
  - id: 2
    name: "サイドバーメニュー実装"
    description: "S-05_wallet_home.yaml の sidebar セクションに基づき、各機能画面へのナビゲーションリンクを持つサイドバーを実装。ハンバーガーメニューによる表示/非表示切り替えも実装。"
  - id: 3
    name: "月移動機能実装"
    description: "前月・次月ボタンによる表示月の変更機能、および表示月変更に伴うデータ再取得・UI更新ロジックを実装。"
  - id: 4
    name: "収支サマリーデータ取得・表示ロジック実装"
    description: "選択された月のアクティブな家計簿について、income_expenses テーブル (D-05) からユーザー別収支、共通収支を取得・集計し、S-05_wallet_home.yaml の形式で表示する。"
  - id: 5
    name: "支払額・支払率データ連携・表示 (T-08完了後対応)"
    description: "T-08 (支払額算出設定) で計算されたユーザー別月次支払額と支払率をホーム画面サマリーに表示する。(本ステップはT-08完了後に実施)"
  - id: 6
    name: "支払期限リスト表示機能実装"
    description: "payment_destinations テーブル (D-06) と現在の表示月から、当月の支払期限リストを生成し表示する。"
  - id: 7
    name: "認証・家計簿参加状態チェック"
    description: "S-05_wallet_home.yaml の auth_required, wallet_membership_required に基づき、適切なアクセス制御を保証する。 (ミドルウェアと連携)"
created_at: 2025-05-17T10:10:00+09:00
updated_at: 2025-05-17T10:10:00+09:00
logs:
  - "2025-05-17: タスクファイル作成" 