id: T-09-wallet-basic-settings
name: "基本設定編集画面 (S-09) 実装"
description: |
  家計簿の基本設定編集画面 (S-09) のUIと機能を実装する。
  家計簿名の変更、参加申請の受付設定、参加コードの管理（再生成、手動設定）、家計簿削除機能を提供する。
  データは wallets テーブル (D-02) と連携する。
status: pending
depends_on: [T-05-wallet-home]
outputs:
  - "S-09 基本設定編集画面の完成されたUI（S-09_basic_settings.yaml 準拠）"
  - "家計簿名編集・保存機能"
  - "参加申請受付ON/OFF設定機能"
  - "参加コード表示・再生成機能"
  - "参加コード手動設定機能（バリデーション含む）"
  - "家計簿削除機能（確認ダイアログ付き、関連データ削除考慮）"
  - "wallets テーブル (D-02) への更新・削除処理"
steps:
  - id: 1
    name: "S-09 UIレイアウト実装"
    description: "S-09_basic_settings.yaml に基づき、ヘッダー、家計簿名入力、参加申請設定ラジオボタン、参加コード管理セクション（現在コード表示、再生成ボタン、手動設定チェックボックス・入力欄）、危険な操作セクション（家計簿削除ボタン）、保存・キャンセルボタンの基本レイアウトを実装。"
  - id: 2
    name: "基本設定読込・表示機能実装"
    description: "アクティブな家計簿の wallets テーブルから既存の設定（家計簿名、参加申請受付状況、参加コードなど）を読み込み、フォームに表示する。"
  - id: 3
    name: "家計簿名・参加申請設定 更新機能実装"
    description: "編集された家計簿名、参加申請受付状況を wallets テーブルに保存する処理を実装。"
  - id: 4
    name: "参加コード管理機能実装"
    description: "参加コードの自動再生成、および手動での新規コード設定（英数字6〜12文字バリデーション含む）機能を実装し、wallets テーブルに保存する。"
  - id: 5
    name: "家計簿削除機能実装"
    description: "家計簿を削除する機能を実装。削除前に確認ダイアログを表示。wallets テーブルから該当レコードを削除。関連するテーブルのデータ（収支、メンバー、設定など）も適切に削除または処理する必要があることを考慮（具体的な削除範囲は要検討・実装）。削除後は家計簿選択画面へ遷移。"
  - id: 6
    name: "設定保存機能実装"
    description: "画面上の全ての変更内容を wallets テーブルに一括で保存する機能を実装。"
created_at: 2025-05-17T10:30:00+09:00
updated_at: 2025-05-17T10:30:00+09:00
logs:
  - "2025-05-17: タスクファイル作成" 